[processor.pylint]
src_dirs = ["src", "scripts"]

[processor.ruff]
src_dirs = ["src", "scripts"]

[processor.mypy]
src_dirs = ["src", "scripts"]

[processor.shellcheck]
src_dirs = ["scripts"]

[processor.htmlhint]
src_dirs = ["src"]

[processor.tidy]
src_dirs = ["src"]
